### ISSUE TITLE
Make PocketPower compatible with MCPE 0.13

### ISSUE THREAD

**Issue by kvetinac97** [byteandahalf/PocketPower#4]
Like adding repeaters, pistons, sticky pistons etc. to MCPE 0.13

**Comment by byteandahalf** [comment]
Making a new mod for this, thanks.

**Comment by kvetinac97** [comment]
Oh OK, what will be its name and when it'll be released?

**Comment by TrinityDevelopers** [comment]
The name is "Redstone Plus".  Byteandahalf has not mentioned any designated release date, but it is approximated to be by the end of the year.

**Comment by kvetinac97** [comment]
Hmm... OK, but I think that MCPE 0.14 will be released by the end of the year...
